import nextImage from 'next/image';
const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/shirt3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/pants1.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/pants2.jpg',
            price: 95,
            brand: 'Zara',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: 'https://raw.githubusercontent.com/basir/next-tailwind-amazona/1edf7cb9c35bc8c3fc3476647add4602cb4ffbbc/public/images/pants3.jpg',
            price: 75,
            brand: 'Casely',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Hot Wheels',
            slug: 'hot-wheels',
            category: 'Toys',
            image: 'https://cdn.akakce.com/z/hot-wheels/hot-wheels-sehir-hayati-serisi-hdr24.jpg',
            price: 5,
            brand: 'Hot Wheels',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'car toy',
        },
        {
            name: 'Hot Wheels',
            slug: 'hot-wheels',
            category: 'Toys',
            image: 'https://cdn.akakce.com/z/hot-wheels/hot-wheels-36-li-araba-koleksiyonu-gwn98.jpg',
            price: 22.5,
            brand: 'Hot Wheels',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'car toy',
        },
    ],
};

export default data;
